const express=require("express")
const router = require("./routes/index")
const { globalErrorHandler } = require("./middleware/error")
const corsConfig = require("./config/corsConfig")
const connectToDb = require("./database/inxex")
connectToDb()
const app =express()
app.use(corsConfig())
app.use(express.json())
app.use('/user',router)
app.use(globalErrorHandler)
app.listen(8000)
